import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}//his meta data has all the content that normal <head>in html has so we dont use it below

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

//At least on root layout file needed, rest we can have more in individual folders.
//It makes a layout around some item.
//so here page.tsx has the page data that will be injected inside this layout.
//we have gobal css file.
